### ISSUE TITLE
file\put() default mode

### ISSUE THREAD

**Issue by bwoebi** [amphp/file#11]
If a file does not yet exist, we have to set a default file permissions mode.

Currently it's a mess:
- NativeDriver sets 0666 [note this is hardcoded, if we decide to not use 0666 by default, we'll need an extra chmod() call then and checking whether the file existed beforehand]
- EioDriver sets 0644
- UvDriver sets 0700

So: what should be the default?

Also, I think we should add a third optional parameter to put() to allow overriding that default.

\cc @trowski @daverandom @kelunik

**Comment by kelunik** [comment]
I guess it should be 644, which is the Linux default IIRC.

**Comment by DaveRandom** [comment]
To follow up on this, after the issue was created we realised that native driver actually passes `0666` to `open(2)` which is then affected by the umask, since by default this is `0022` the effective default permissions used by the native driver are also `0644`.

Therefore the least surprising option is probably `0644` across the board for all drivers.

`Driver::open()` and `Driver::put()` should have an optional arg to set this per-call. Possibly `Driver` should also have a `setDefaultFilePermissions()` function to set this app-wide? If I have an app where the specs change so that I now need to set all new files to be `0600`, this could be a useful feature. The could possibly be implemented as `setUmask()` but this always seemed like an unnecessarily complex and non-obvious API to me.

**Comment by bwoebi** [comment]
I wonder whether we should just pass 0666 and have the umask() applied to it implicitly (in case anyone uses that), just to be consistent? Sounds like the best way to me.

What's the point of a _setUmask()_? umask is not an uv/eio thing, it's global and setting it doesn't ever involve I/O. (e.g. glibc is implementing it as just setting a [process] global variable and applying it right before submitting the real sycall)

**Comment by kelunik** [comment]
@DaveRandom No, please no global state with permissions.
