### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tuefekci** [amphp/file#63]
Hello Guys,

This is not a real issue i just did not find another way to communicate which is available to me.

Perhaps i just cant find it but is there a reason why there is no getting started or otherwise documentation for the file api?

I switched one of my projects from react and started to compare my available options and this somehow confused me a bit because the basic amp decumentation is already from an user experience not so great, and my reason for switching was file system problems under windows. (which works perfectly fine in amp)

I just dont quite understand it, because all the work for documentation is in the code so its just missing generation for a simple api reference atleast. Perhaps its not needed for most people and i also dont need it to work with the api but for Newcomers or people with less experience it could help. Because the first thing i usually try in a new environment are the basics like writing files making connections etc.

If all this stuff exists and im just not finding it perhaps linking it in the readme more promiment could help people get faster access to amp which has a clearer code base and is better to understand in source than similar projects, but somehow more confusing in its documentation atleast from my standpoint with just some hours into it.

Thanks this is not a real issue but i just could not figure out why this is and thought that perhaps its overlooked because you guys work with it all the time and spend time to write all the comments and references needed so its a somehow a shame if somebody would not use it because of that.

**Comment by kelunik** [comment]
Hey @tuefekci,

don't worry, opening an issue here is perfectly fine. You can find other ways on https://amphp.org/support, but it's not up-to-date, as it's still mentioning IRC instead of our telegram group, I thought I had fixed that.

It's true that we currently don't have any documentation in this repository except in the source itself. Most generated API references aren't particularly helpful to me, at least not for getting started. Generated API references usually miss explaining how different parts work together. We usually include an `examples` directory to get people started, but it's missing in this repository as well.

Any help with writing documentation would be appreciated, such as adding examples. We're currently focused on getting all libraries compatible with [Revolt](https://github.com/revoltphp/event-loop) and fibers, which will greatly ease getting started into async PHP, and which will power Amp v3 under the hood.

**Comment by kelunik** [comment]
Basic documentation is now present in the `README.md`.
